### ISSUE TITLE
Speech to text docs refer to user/pass auth...

### ISSUE THREAD

**Issue by jamesoflol** [IBM-Bluemix-Docs/speech-to-text#69]
Speech to text docs refer to user/pass auth, but user/pass credentials are not provided. On the service credentials page, I am given an API key. I can't even try out the API with CURL, given that all the doc refers to a user/pass for that.

I decided to give Bluemix speech-to-text the benefit of the doubt by going straight to the Node SDK, but it is also currently not operational - https://github.com/watson-developer-cloud/node-sdk/pull/717

Are all new accounts given only an API key? I must be missing something huge, because I don't understand how anyone could actually use the service, if we're given API keys, but only user/pass works with either CURL or the SDK.

**Comment by jeffpk62** [comment]
Hi, James,

Authentication via IAM API key is fairly new and is available only in select geographies (Sydney and US East at this time).  All existing service instances and new services instances created in other regions continue to use service credentials.  The documentation is in the process of being converted to the new authentication mechanism.  I sincerely apologize for the transient inconsistency; I know it's pretty confusing.

Until that conversion is complete, which should occur very soon, you can learn more about where the service has been converted to IAM authentication and about IAM itself in the release notes for the service:  [New API authentication process](https://console.bluemix.net/docs/services/speech-to-text/release-notes.html#new-authentication).

Fortunately, using an API key instead of service credentials for authentication is really pretty straightforward.  With the `-u` (`--user`) option of a cURL command, replace

`-u "{username}:{password}"`

with 

`-u "apikey:{apikey}"`

Substitute your API key for `{apikey}` in the option.  

If you are using any of the SDKs documented in the API reference, the substitution is similar but may include additional subtle differences.  The reference is also in the process of being converted over to use API keys and will be complete soon.

Please let me know if this information helps, and thanks for raising the issue!

**Comment by SirSpidey** [comment]
@jamesoflol, Sorry that you can't find the correct information for your service instance. We get it. 

To add to what Jeff provided, if you use the SDKs, you can see examples in the **Authentication** section of the API reference. For example, Node: https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/node.html?node#authentication

The READMEs in the SDKs also provide some information about API keys. Again, for node: https://github.com/watson-developer-cloud/node-sdk#iam

**Comment by jamesoflol** [comment]
Hey guys. Thanks for the info. Spidey: My issue with the SDK was not that I couldn't find the info, but that the SDK wasn't actually working with the new auth method, see linked gh issue.
Jeff, thanks for that clarification. Good luck with the rest of the conversion.
